name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix workspace permissions
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Run Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twinklehub-apk
          path: bin/*.apk
          
